### ISSUE TITLE
Cambiar el nombre de la carpeta en src

### ISSUE THREAD

**Issue by fabriziotonin** [silmedina/rollingtimes#3]
El nombre de la carpeta common no coincide con el nombre de las rutas donde es importado provoca error en footer y AuthenticationRoute  (cambiar el nombre de la carpeta por mayúscula)
![image](https://user-images.githubusercontent.com/51201108/126375485-46250fa3-7efb-4ab0-bf0a-f6da439ec51e.png)

**Comment by silmedina** [comment]
@fabriziotonin done
