### ISSUE TITLE
Arreglar warnings

### ISSUE THREAD

**Issue by fabriziotonin** [silmedina/rollingtimes#4]
- Falta la key al en el componente CategoriaListadoNoticias, BuscarNoticias, al hacer el map
![image](https://user-images.githubusercontent.com/51201108/126380012-48c606d6-0322-4e72-b199-c848277aa9fe.png)

- En CategoriaListadoNoticias, Tabs Cambiar Card.text por otra etiqueta para evitar el problema de nesting <p> y utilizar su estilo o reemplazar h6 y footer por span u otra etiqueta que permita estar dentro de un <p>

![image](https://user-images.githubusercontent.com/51201108/126380862-5e80375c-ddad-4973-abfc-b5f9d89c66fb.png)

**Comment by silmedina** [comment]
@fabriziotonin done

**Comment by fabriziotonin** [comment]
El error perciste en la en la url http://localhost:3000/categorias/listado-noticias/Deporte logeado como admin y otras categorias
![image](https://user-images.githubusercontent.com/51201108/127528759-d59f7af6-b4ac-4b9e-8dfc-331e81f6775d.png)
